/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Proveedores;
import Logica.Lconexion;
import java.awt.Point;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author levd
 */
public class FrmBuscarProvedor extends javax.swing.JDialog {
java.sql.Connection con = Lconexion.GetConnection();
    /**
     * Creates new form FrmBuscarProvedor
     */
    public FrmBuscarProvedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrarBuscar("");
        tblproveedorb.getColumnModel().getColumn(0).setMaxWidth(0);
        tblproveedorb.getColumnModel().getColumn(0).setMinWidth(0);
        tblproveedorb.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
public void mostrarBuscar(String proveedores){
        DefaultTableModel miModelo;
//        lUsuarios fn = new lUsuarios();
        
        Proveedores fts = new Proveedores();
        FrmProveedores fun = new FrmProveedores();
//        fts.setNombre(txtNombre.getText());
//        miModelo = fts.mostrarProveedor(fts);
        miModelo = fun.mostrarProveedor(fts);
        tblproveedorb.setModel(miModelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblproveedorb = new javax.swing.JTable();
        txtFiltrar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proveedores");

        tblproveedorb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblproveedorb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblproveedorbMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblproveedorb);

        txtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltrarKeyPressed(evt);
            }
        });

        jLabel1.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarKeyPressed
        // TODO add your handling code here:
                  DefaultTableModel miModelo=null;
//     DefaultTableModel dm = (DefaultTableModel) tblLineas.getModel();
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
//        tblLineas.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(consulta));

     String[] titulos = {"Nombre","telefono","domicilio"};
        String[] registros = new String[50];
        String sql = "SELECT *FROM tblproveedores WHERE idproveedores LIKE '%" + txtFiltrar.getText() + "%' "
                + "OR Nombre LIKE '%" + txtFiltrar.getText() + "%'"
                + "OR telefono LIKE '%" + txtFiltrar.getText() + "%'"
                + "OR domicilio LIKE '%" + txtFiltrar.getText() + "%'";
               
        miModelo = new DefaultTableModel(null, titulos);
        java.sql.Connection cc = Lconexion.GetConnection();
//        Connection conect = cc.conexion();
        try {
            Statement st =con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
//                registros[0] = rs.getString("idproveedores");
                registros[0] = rs.getString("Nombre");
                registros[1] = rs.getString("telefono");
                registros[2] = rs.getString("domicilio");
             
                miModelo.addRow(registros);
            }
            tblproveedorb.setModel(miModelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtFiltrarKeyPressed

    private void tblproveedorbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproveedorbMousePressed
        // TODO add your handling code here:
        JTable tbl = (JTable) evt.getSource();
//        Point pt = evt.getPoint();
//        int row = tbl.rowAtPoint(pt);
        if (evt.getClickCount()==2) {
            String id = tblproveedorb.getValueAt(tblproveedorb.getSelectedRow(),0).toString();
       String proveedor= tblproveedorb.getValueAt(tblproveedorb.getSelectedRow(),1).toString();
       FrmFacturas.setProveedore(id,proveedor);
       this.dispose();
        
        }
    }//GEN-LAST:event_tblproveedorbMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmBuscarProvedor dialog = new FrmBuscarProvedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblproveedorb;
    private javax.swing.JTextField txtFiltrar;
    // End of variables declaration//GEN-END:variables
}
